# Generated by Django 3.0.7 on 2020-08-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50)),
                ('amail', models.EmailField(max_length=254)),
                ('ausername', models.CharField(max_length=50)),
                ('apassword', models.CharField(max_length=50)),
            ],
        ),
    ]
