# Generated by Django 3.0.7 on 2020-10-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loggedin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplyJob',
        ),
        migrations.DeleteModel(
            name='Cand_details',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
