# Generated by Django 3.0.7 on 2020-08-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='cname',
        ),
        migrations.AddField(
            model_name='job',
            name='jcname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
