# Generated by Django 3.0.7 on 2020-08-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200831_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jcname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='jdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='lastapply',
            field=models.DateTimeField(null=True),
        ),
    ]
