# Generated by Django 3.0.7 on 2020-08-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20200831_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='maxage',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='no_of_openings',
            field=models.IntegerField(default=1),
        ),
    ]
