# Generated by Django 3.0.7 on 2020-09-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200831_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cand_details',
            name='regdate',
        ),
    ]
