# Generated by Django 3.0.7 on 2020-09-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20200916_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.Candidate'),
        ),
    ]
