# Generated by Django 3.0.7 on 2020-09-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='candidate',
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.Job'),
        ),
    ]
