# Generated by Django 3.0.7 on 2020-10-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20200926_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=50)),
                ('jobtype', models.CharField(max_length=50)),
                ('apply_date', models.DateTimeField(auto_now=True)),
                ('comname', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='job',
        ),
        migrations.AlterField(
            model_name='company',
            name='cregdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
