# Generated by Django 3.0.7 on 2020-10-25 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20201006_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='apply_date',
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='comname',
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='jobtitle',
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='jobtype',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.Job'),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.Candidate'),
        ),
    ]
