# Generated by Django 3.0.7 on 2020-10-30 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20201025_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='cand_details',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.Candidate'),
        ),
    ]
