# Generated by Django 3.0.7 on 2020-10-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_cand_details_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cand_details',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='cand_details',
            name='lastname',
        ),
    ]
